// Chunked Gated DeltaNet prefill: one fused, state-resident kernel.
// Port of cacao iter20 (fused_state_resident_single_kernel/fine_slab_dv16_384blk),
// config FUSE=1 TCINV=1 REB=1 FOLD=0 TRB=0, CHUNK=16, DV_TILE=32, MINBLOCKS=3.
//
// Grid: (kHv * (kD / DV_TILE), B) blocks of NTHREADS. Block (h, dv0, b) owns the slab
// S[kD x DV_TILE] of head h (state columns dv0 .. dv0+31) in mma accumulator
// registers for the whole sequence and walks it CHUNK tokens at a time.
//
// Layouts (fp32, row-major):
//   q, k    [T][kHk][kD]             already L2-normalised by the graph; scale applied here
//   v       [T][.][kD]               token stride v_tok_stride, head h at +h*kD (fused-QKV view)
//   g, beta [T][kHv]                 g = per-token log decay, <= 0
//   o       [T][kHv][kD]
//   s0, st  [kHv][kD (v)][kD (k)]    ggml state layout, k fastest
// Requires kD == DD, kHv % kHk == 0. Ampere+ (mma.sync m16n8k16 fp16, ldmatrix).
//
// Per chunk, two block barriers: bar2 (Wwin products ready) and bar4 (chunk end) --
// none at the top -- chunk c+1's q/k/tables are staged right after bar2 of chunk c into
// buffers that are dead by then (Qs, the other Kh parity, the single-buffered tables) or
// parity double-buffered (C2). The vnew tiles are produced by the warp that consumes them.
//
// Provenance: generated by an automated kernel-search pipeline ("cacao": an LLM
// iteratively rewriting the kernel against a KTT autotuning benchmark of this op at
// Qwen3.8-27B dimensions), then ported by hand to the ggml boundary: decay applied
// only as bounded differences exp(G_i - G_j), GQA index h % num_k_heads, V through
// the fused-QKV token stride, state transposed to ggml's [head][v][k], batch on
// grid.y. See the PR description for the measurements.

#include "gated_delta_net.cuh"
#include <cuda_fp16.h>
#include <cstdlib>

// Ampere+ NVIDIA only: the kernel is inline-PTX mma.sync.m16n8k16 (fp16) + ldmatrix.
// Everything below compiles to a stub elsewhere; the runtime dispatch never selects it there.
#if !defined(GGML_USE_HIP) && !defined(GGML_USE_MUSA) && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= GGML_CUDA_CC_AMPERE
#    define GDN_FUSED_AVAILABLE 1
#endif

constexpr int CHUNK     = 16;            // tokens per chunk = one mma M tile
constexpr int DV_TILE   = 32;            // state columns per block
constexpr int DD        = 128;           // head dim; the fragment geometry is specialised to it
constexpr int NWARPS    = 8;
constexpr int NTHREADS  = NWARPS * 32;
constexpr int MINBLOCKS = 3;             // 85-register cap -> 3 blocks/SM

__device__ __forceinline__ __half f2h(float x) {
    return __float2half_rn(fminf(fmaxf(x, -65504.f), 65504.f));
}

__device__ __forceinline__ void mma16816(float c[4], unsigned a0, unsigned a1,
                                         unsigned a2, unsigned a3,
                                         unsigned b0, unsigned b1) {
    asm volatile(
        "mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 "
        "{%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\n"
        : "+f"(c[0]), "+f"(c[1]), "+f"(c[2]), "+f"(c[3])
        : "r"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(b0), "r"(b1));
}

__device__ __forceinline__ void ldsm4(const void* p, unsigned& r0, unsigned& r1,
                                      unsigned& r2, unsigned& r3) {
    unsigned a = (unsigned)__cvta_generic_to_shared(p);
    asm volatile("ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%0,%1,%2,%3}, [%4];\n"
                 : "=r"(r0), "=r"(r1), "=r"(r2), "=r"(r3) : "r"(a));
}

__device__ __forceinline__ void ldsm2(const void* p, unsigned& r0, unsigned& r1) {
    unsigned a = (unsigned)__cvta_generic_to_shared(p);
    asm volatile("ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%0,%1}, [%2];\n"
                 : "=r"(r0), "=r"(r1) : "r"(a));
}

__device__ __forceinline__ void ldsm2t(const void* p, unsigned& r0, unsigned& r1) {
    unsigned a = (unsigned)__cvta_generic_to_shared(p);
    asm volatile("ldmatrix.sync.aligned.m8n8.x2.trans.shared.b16 {%0,%1}, [%2];\n"
                 : "=r"(r0), "=r"(r1) : "r"(a));
}

__device__ __forceinline__ void ldsm4t(const void* p, unsigned& r0, unsigned& r1,
                                       unsigned& r2, unsigned& r3) {
    unsigned a = (unsigned)__cvta_generic_to_shared(p);
    asm volatile("ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 {%0,%1,%2,%3}, [%4];\n"
                 : "=r"(r0), "=r"(r1), "=r"(r2), "=r"(r3) : "r"(a));
}

// Bank-conflict swizzle of the 16-byte column unit within a row. umask = row width
// in 16B units minus one (7 for 256 B rows, 3 for 64 B rows).
__device__ __forceinline__ int swz(int r, int c16, int umask) { return c16 ^ (r & umask); }

__global__ void __launch_bounds__(NTHREADS, MINBLOCKS)
gdn_fused(int kT, int kHk, int kHv, int kD,
          const float* __restrict__ qp, const float* __restrict__ kp,
          const float* __restrict__ vp, const float* __restrict__ gp,
          const float* __restrict__ bp, float* __restrict__ op,
          const float* __restrict__ s0p, float* __restrict__ stp,
          long long v_tok_stride)
{
#ifndef GDN_FUSED_AVAILABLE
    GGML_UNUSED_VARS(kT, kHk, kHv, kD, qp, kp, vp, gp, bp, op, s0p, stp, v_tok_stride);
    NO_DEVICE_CODE;
#else
    __shared__ __align__(16) __half Qs[CHUNK * DD];            // q chunk (scaled)
    __shared__ __align__(16) __half Kh[2 * CHUNK * DD];        // k chunk, double-buffered by chunk parity
    __shared__ __align__(16) __half P[CHUNK * CHUNK];          // masked Q K^T
    __shared__ __align__(16) __half VbWh[2 * CHUNK * DV_TILE]; // [beta*v | K S]
    __shared__ __align__(16) __half Sh[DD * DV_TILE];          // S staged fp16
    __shared__ __align__(16) __half Vn2[2 * CHUNK * DV_TILE];  // C2 .* vnew, one copy per warp half
    __shared__ __align__(16) __half Vn[CHUNK * DV_TILE];       // vnew (output operand)
    __shared__ __align__(16) __half TileA1[256];               // inverse scratch: A21 in the top-left 8x8
    __shared__ __align__(16) __half TileA2[256];               // inverse scratch: T22 in the top-left 8x8
    __shared__ __align__(16) __half Btop[128];                 // inverse scratch: 16x8 B operand (T11, then M4)
    __shared__ __align__(16) float A[CHUNK * CHUNK];           // gram; then fp16 [T | -T diag(Cc)]
    __shared__ float B[CHUNK], Cc[CHUNK], EX[CHUNK], Gc[CHUNK];
    __shared__ float C2[2 * CHUNK];                            // parity double-buffered (read after bar2)
    __shared__ float s_gl;

    __half* const Vb  = VbWh;
    __half* const Wh  = VbWh + CHUNK * DV_TILE;
    // Each warp half (0-3, 4-7) gets its own Vn2 copy: warps w and w+4 compute the same
    // tile, and separate copies make every store single-writer (clean under racecheck)
    // instead of an identical-byte WAW.

    __half* const Th  = reinterpret_cast<__half*>(A);
    __half* const TCc = Th + CHUNK * CHUNK;

    // blockIdx.y selects the sequence: every pointer is offset to sequence b here,
    // so the rest of the kernel is single-sequence.
    {
        const long long b = blockIdx.y;
        qp  += b * kT * kHk * kD;   kp  += b * kT * kHk * kD;
        vp  += b * kT * v_tok_stride;
        gp  += b * kT * kHv;        bp  += b * kT * kHv;
        op  += b * kT * kHv * kD;
        s0p += b * kHv * kD * kD;   stp += b * kHv * kD * kD;
    }
    const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
    const int h    = blockIdx.x / (kD / DV_TILE);
    const int dv0  = (blockIdx.x % (kD / DV_TILE)) * DV_TILE;
    const int qkh  = h % kHk;
    const float scale = 1.f / sqrtf((float)kD);

    const int nt  = warp & 3;
    const int mt0 = 4 * (warp >> 2);
    const int gr  = lane >> 2, tig = lane & 3;
    const int jbase = 8 * nt + 2 * tig;
    const bool o_warp = warp >= 4;                 // o-tile == state n-tile nt
    __half* const Vn2g = Vn2 + (warp >> 2) * (CHUNK * DV_TILE);   // this warp half's copy
    const int  w2 = warp - 2;                      // warps 2-3: P half / Vb rows

    float  Sreg[4][4];
    float4 pq, pk;
    float  pgv, pbv;

    auto sts_sh = [&]() {
        #pragma unroll
        for (int mt = 0; mt < 4; ++mt) {
            const int d0 = 16 * (mt0 + mt) + gr;
            const int c0 = swz(d0, nt, 3) << 3, c8 = swz(d0 + 8, nt, 3) << 3;
            *reinterpret_cast<__half2*>(&Sh[d0 * DV_TILE + c0 + 2 * tig]) =
                __halves2half2(f2h(Sreg[mt][0]), f2h(Sreg[mt][1]));
            *reinterpret_cast<__half2*>(&Sh[(d0 + 8) * DV_TILE + c8 + 2 * tig]) =
                __halves2half2(f2h(Sreg[mt][2]), f2h(Sreg[mt][3]));
        }
    };

    // Warp 0. Every exponential has a non-positive argument; the masked intra-chunk
    // factors exp(G_i - G_j) are formed at their use sites from Gc.
    auto decay_tables = [&](int rows, int buf) {
        float s = pgv;
        #pragma unroll
        for (int o = 1; o < 16; o <<= 1) {
            const float y = __shfl_up_sync(~0u, s, o);
            if (lane >= o) s += y;
        }
        const float glt = __shfl_sync(~0u, s, rows - 1);
        if (lane == 0) s_gl = glt;
        if (lane < CHUNK) {
            const float ex = __expf(s);
            B[lane]  = pbv;
            EX[lane] = ex;
            Gc[lane] = s;
            Cc[lane] = pbv * ex;
            C2[buf * CHUNK + lane] = __expf(glt - s);
        }
    };

    auto prefetch = [&](int tn) {
        const int t = tn + warp;
        if (t < kT) {
            const long long base = ((long long)t * kHk + qkh) * kD + 4 * lane;
            pq = *reinterpret_cast<const float4*>(qp + base);
            pk = *reinterpret_cast<const float4*>(kp + base);
        } else {
            pq = pk = make_float4(0.f, 0.f, 0.f, 0.f);
        }
        if (warp == 0) {
            const int tg = tn + lane;
            const bool ok = lane < CHUNK && tg < kT;
            pgv = ok ? gp[(long long)tg * kHv + h] : 0.f;
            pbv = ok ? bp[(long long)tg * kHv + h] : 0.f;
        }
    };

    auto sts_row4 = [&](__half* tile, int i, int j4, float4 r) {
        __half2* d = reinterpret_cast<__half2*>(&tile[i * DD + (swz(i, j4 >> 3, 7) << 3) + (j4 & 7)]);
        d[0] = __halves2half2(f2h(r.x), f2h(r.y));
        d[1] = __halves2half2(f2h(r.z), f2h(r.w));
    };

    auto stage_qk = [&](int t0, int buf) {
        __half* const Khb = Kh + buf * CHUNK * DD;
        const int j4 = 4 * lane;
        const int t1 = t0 + warp + NWARPS;
        float4 q1 = make_float4(0.f, 0.f, 0.f, 0.f), k1 = q1;
        if (t1 < kT) {
            const long long base = ((long long)t1 * kHk + qkh) * kD + j4;
            q1 = *reinterpret_cast<const float4*>(qp + base);
            k1 = *reinterpret_cast<const float4*>(kp + base);
        }
        sts_row4(Qs,  warp,          j4, make_float4(pq.x * scale, pq.y * scale, pq.z * scale, pq.w * scale));
        sts_row4(Khb, warp,          j4, pk);
        sts_row4(Qs,  warp + NWARPS, j4, make_float4(q1.x * scale, q1.y * scale, q1.z * scale, q1.w * scale));
        sts_row4(Khb, warp + NWARPS, j4, k1);
    };

    // Warps 0-1: A = -beta_i exp(G_i - G_j) (k_i . k_j), j < i; warp w stores columns 8w..8w+7.
    auto gram_A_half = [&](const __half* khb) {
        float acc[4] = {0.f, 0.f, 0.f, 0.f};
        unsigned a0, a1, a2, a3;
        ldsm4(&khb[(lane & 15) * DD + (swz(lane & 15, lane >> 4, 7) << 3)], a0, a1, a2, a3);
        #pragma unroll
        for (int ks = 0; ks < 8; ++ks) {
            const unsigned A0 = a0, A1 = a1, A2 = a2, A3 = a3;
            if (ks + 1 < 8) {
                const int k16 = 16 * (ks + 1);
                ldsm4(&khb[(lane & 15) * DD + (swz(lane & 15, (k16 >> 3) + (lane >> 4), 7) << 3)],
                      a0, a1, a2, a3);
            }
            if (warp == 0) mma16816(acc, A0, A1, A2, A3, A0, A2);
            else           mma16816(acc, A0, A1, A2, A3, A1, A3);
        }
        const int i0 = gr, i1 = i0 + 8;
        const int jj = 8 * warp + 2 * tig;
        const float mA = -B[i0], mB = -B[i1];
        const float g0 = Gc[i0], g1 = Gc[i1];
        const float gj0 = Gc[jj], gj1 = Gc[jj + 1];
        *reinterpret_cast<float2*>(&A[i0 * CHUNK + jj]) = make_float2(
            (jj     < i0) ? mA * __expf(g0 - gj0) * acc[0] : 0.f,
            (jj + 1 < i0) ? mA * __expf(g0 - gj1) * acc[1] : 0.f);
        *reinterpret_cast<float2*>(&A[i1 * CHUNK + jj]) = make_float2(
            (jj     < i1) ? mB * __expf(g1 - gj0) * acc[2] : 0.f,
            (jj + 1 < i1) ? mB * __expf(g1 - gj1) * acc[3] : 0.f);
        __syncwarp();
    };

    // Warps 0-1 together: T = (I - A)^{-1}. Diagonal 8x8 blocks by forward substitution
    // (warp 0: T11, warp 1: T22, written back into A in fp32); the off-diagonal block
    // T21 = T22 * A21 * T11 as two tensor-core mma out of dedicated fp16 scratch. Then
    // fp16 Th = T and TCc = -T diag(Cc) are written over A. Reads of A before the named
    // barrier are own-warp only (gram_A_half's __syncwarp fences them).
    auto invert_T = [&]() {
        const int base = warp << 3;
        float tc[8];
        if (lane < 8) {
            const int ccol = base + lane;
            #pragma unroll
            for (int r = 0; r < 8; ++r) {
                const int rg = base + r;
                float v;
                if (rg < ccol) v = 0.f;
                else if (rg == ccol) v = 1.f;
                else {
                    v = A[rg * CHUNK + ccol];
                    #pragma unroll
                    for (int m = 1; m < 8; ++m)
                        if (base + m > ccol && base + m < rg)
                            v += A[rg * CHUNK + base + m] * tc[m];
                }
                tc[r] = v;
            }
            #pragma unroll
            for (int r = 0; r < 8; ++r)
                A[(base + r) * CHUNK + ccol] = tc[r];
        }
        __syncwarp();
        {   // fp32 -> fp16 scratch: warp 0: T11 -> Btop rows 0-7, A21 -> TileA1; warp 1: T22 -> TileA2
            const int r = lane >> 2, cp = lane & 3;
            if (warp == 0) {
                const float2 t = *reinterpret_cast<const float2*>(&A[r * CHUNK + 2 * cp]);
                *reinterpret_cast<__half2*>(&Btop[r * 8 + 2 * cp]) = __halves2half2(f2h(t.x), f2h(t.y));
                const float2 u = *reinterpret_cast<const float2*>(&A[(8 + r) * CHUNK + 2 * cp]);
                *reinterpret_cast<__half2*>(&TileA1[r * 16 + 2 * cp]) = __halves2half2(f2h(u.x), f2h(u.y));
            } else {
                const float2 t = *reinterpret_cast<const float2*>(&A[(8 + r) * CHUNK + 8 + 2 * cp]);
                *reinterpret_cast<__half2*>(&TileA2[r * 16 + 2 * cp]) = __halves2half2(f2h(t.x), f2h(t.y));
            }
        }
        float t21[2] = {0.f, 0.f};
        if (warp == 0) {
            __syncwarp();
            unsigned a0, a1, a2, a3, b0, b1;
            float acc[4] = {0.f, 0.f, 0.f, 0.f};
            ldsm4(&TileA1[(lane & 15) * 16 + ((lane >> 4) << 3)], a0, a1, a2, a3);
            ldsm2t(&Btop[(lane & 15) * 8], b0, b1);
            mma16816(acc, a0, a1, a2, a3, b0, b1);                      // M4 = A21 * T11
            *reinterpret_cast<__half2*>(&Btop[gr * 8 + 2 * tig]) = __halves2half2(f2h(acc[0]), f2h(acc[1]));
            __syncwarp();
        }
        asm volatile("bar.sync 1, 64;" ::: "memory");                  // TileA2 + M4 visible; fp32 A reads done
        if (warp == 0) {
            unsigned a0, a1, a2, a3, b0, b1;
            float acc2[4] = {0.f, 0.f, 0.f, 0.f};
            ldsm4(&TileA2[(lane & 15) * 16 + ((lane >> 4) << 3)], a0, a1, a2, a3);
            ldsm2t(&Btop[(lane & 15) * 8], b0, b1);
            mma16816(acc2, a0, a1, a2, a3, b0, b1);                     // T21 = T22 * M4
            t21[0] = acc2[0]; t21[1] = acc2[1];
        }
        if (lane < 8) {
            const int ccol = base + lane;
            const float ccv = Cc[ccol];
            #pragma unroll
            for (int r = 0; r < 8; ++r) {
                Th[(base + r) * 16 + ccol]  = f2h(tc[r]);
                TCc[(base + r) * 16 + ccol] = f2h(-tc[r] * ccv);
            }
        }
        if (warp == 0) {
            const float cc0 = Cc[2 * tig], cc1 = Cc[2 * tig + 1];
            *reinterpret_cast<__half2*>(&Th[(8 + gr) * 16 + 2 * tig])  = __halves2half2(f2h(t21[0]), f2h(t21[1]));
            *reinterpret_cast<__half2*>(&TCc[(8 + gr) * 16 + 2 * tig]) = __halves2half2(f2h(-t21[0] * cc0), f2h(-t21[1] * cc1));
        }
        if (lane >= 8 && lane < 16) {
            const int zr = (warp << 2) + ((lane - 8) >> 1);
            const int zc = 8 + 2 * (lane & 1);
            const __half2 z = __half2half2(__ushort_as_half(0));
            *reinterpret_cast<__half2*>(&Th[zr * 16 + zc])      = z;
            *reinterpret_cast<__half2*>(&Th[zr * 16 + zc + 4])  = z;
            *reinterpret_cast<__half2*>(&TCc[zr * 16 + zc])     = z;
            *reinterpret_cast<__half2*>(&TCc[zr * 16 + zc + 4]) = z;
        }
        __syncwarp();
    };

    // Warps 2-3: P[i][j] = exp(G_i - G_j) (q_i . k_j), j <= i; warp w stores columns 8(w-2)..+7.
    // The B chain loads only this warp's 8 token rows of Kh (ldsm2, both matrices = same rows).
    auto p_gram_half = [&](const __half* khb) {
        float acc[4] = {0.f, 0.f, 0.f, 0.f};
        unsigned a0, a1, a2, a3, b0, b1;
        const int rr = 8 * w2 + (lane & 7);
        ldsm4(&Qs[(lane & 15) * DD + (swz(lane & 15, lane >> 4, 7) << 3)], a0, a1, a2, a3);
        ldsm2(&khb[rr * DD + (swz(rr, ((lane >> 3) & 1), 7) << 3)], b0, b1);
        #pragma unroll
        for (int ks = 0; ks < 8; ++ks) {
            const unsigned A0 = a0, A1 = a1, A2 = a2, A3 = a3;
            const unsigned B0 = b0, B1 = b1;
            if (ks + 1 < 8) {
                const int k16 = 16 * (ks + 1);
                ldsm4(&Qs[(lane & 15) * DD + (swz(lane & 15, (k16 >> 3) + (lane >> 4), 7) << 3)],
                      a0, a1, a2, a3);
                ldsm2(&khb[rr * DD + (swz(rr, (k16 >> 3) + ((lane >> 3) & 1), 7) << 3)], b0, b1);
            }
            mma16816(acc, A0, A1, A2, A3, B0, B1);
        }
        const int i0 = gr, i1 = i0 + 8;
        const int jj = 8 * w2 + 2 * tig;
        const float g0 = Gc[i0], g8 = Gc[i1];
        const float gj0 = Gc[jj], gj1 = Gc[jj + 1];
        *reinterpret_cast<__half2*>(&P[i0 * CHUNK + jj]) = __halves2half2(
            f2h((jj     <= i0) ? __expf(g0 - gj0) * acc[0] : 0.f),
            f2h((jj + 1 <= i0) ? __expf(g0 - gj1) * acc[1] : 0.f));
        *reinterpret_cast<__half2*>(&P[i1 * CHUNK + jj]) = __halves2half2(
            f2h((jj     <= i1) ? __expf(g8 - gj0) * acc[2] : 0.f),
            f2h((jj + 1 <= i1) ? __expf(g8 - gj1) * acc[3] : 0.f));
        __syncwarp();
    };

    // ---- prologue: s0 loads (ggml [v][k] -> fragment S[k][v]) overlapped with chunk 0 staging ----
    float2 st0[4], st1[4];
    {
        const float* __restrict__ s0h = s0p + (long long)h * kD * kD + (long long)(dv0 + jbase) * kD;
        #pragma unroll
        for (int mt = 0; mt < 4; ++mt) {
            const int d0 = 16 * (mt0 + mt) + gr;
            st0[mt] = make_float2(s0h[d0],     s0h[kD + d0]);
            st1[mt] = make_float2(s0h[d0 + 8], s0h[kD + d0 + 8]);
        }
    }
    prefetch(0);
    // Inverse scratch: the rows/quadrants that multiply live operands must be finite zeros.
    if (warp == 0) {
        *reinterpret_cast<__half2*>(&Btop[64 + 2 * lane]) = __half2half2(__ushort_as_half(0));
    } else if (warp == 1) {
        *reinterpret_cast<__half2*>(&TileA1[(lane >> 2) * 16 + 8 + 2 * (lane & 3)]) = __half2half2(__ushort_as_half(0));
        *reinterpret_cast<__half2*>(&TileA2[(lane >> 2) * 16 + 8 + 2 * (lane & 3)]) = __half2half2(__ushort_as_half(0));
    }
    stage_qk(0, 0);
    if (warp == 0) decay_tables(min(CHUNK, kT), 0);
    #pragma unroll
    for (int mt = 0; mt < 4; ++mt) {
        Sreg[mt][0] = st0[mt].x; Sreg[mt][1] = st0[mt].y;
        Sreg[mt][2] = st1[mt].x; Sreg[mt][3] = st1[mt].y;
    }
    sts_sh();
    __syncthreads();

    const int NC = (kT + CHUNK - 1) / CHUNK;
    for (int c = 0; c < NC; ++c) {
        const int t0 = c * CHUNK;
        const __half* khb = Kh + (c & 1) * CHUNK * DD;

        if (c + 1 < NC) prefetch(t0 + CHUNK);             // consumed after bar2
        const float dl = __expf(s_gl);
        float acco[4] = {0.f, 0.f, 0.f, 0.f};

        // ---- Wwin: gram + inverse (warps 0-1); beta*v + P halves (warps 2-3); Q S + K S (warps 4-7) ----
        if (warp < 2) {
            gram_A_half(khb);
            invert_T();
        }
        if (warp >= 2 && warp < 4) {
            const int iv  = w2 * 8 + (lane >> 2);
            const int j4v = 4 * (lane & 3);
            const int tv  = t0 + iv;
            const float* vrow = vp + (long long)tv * v_tok_stride + (long long)h * kD + dv0 + j4v;
            const float4 v0 = (tv < kT) ? *reinterpret_cast<const float4*>(vrow)      : make_float4(0.f, 0.f, 0.f, 0.f);
            const float4 v1 = (tv < kT) ? *reinterpret_cast<const float4*>(vrow + 16) : make_float4(0.f, 0.f, 0.f, 0.f);
            p_gram_half(khb);
            const float biv = B[iv];
            __half2* const v2a = reinterpret_cast<__half2*>(&Vb[iv * DV_TILE + (swz(iv, j4v >> 3, 3) << 3) + (j4v & 7)]);
            v2a[0] = __halves2half2(f2h(biv * v0.x), f2h(biv * v0.y));
            v2a[1] = __halves2half2(f2h(biv * v0.z), f2h(biv * v0.w));
            const int j4w = j4v + 16;
            __half2* const v2b = reinterpret_cast<__half2*>(&Vb[iv * DV_TILE + (swz(iv, j4w >> 3, 3) << 3) + (j4w & 7)]);
            v2b[0] = __halves2half2(f2h(biv * v1.x), f2h(biv * v1.y));
            v2b[1] = __halves2half2(f2h(biv * v1.z), f2h(biv * v1.w));
        }
        if (o_warp) {
            float acc2[4] = {0.f, 0.f, 0.f, 0.f};
            unsigned a0, a1, a2, a3, bh0, bh1;
            ldsm4(&Qs[(lane & 15) * DD + (swz(lane & 15, lane >> 4, 7) << 3)], a0, a1, a2, a3);
            ldsm2t(&Sh[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], bh0, bh1);
            #pragma unroll
            for (int ks = 0; ks < 8; ++ks) {
                const unsigned A0 = a0, A1 = a1, A2 = a2, A3 = a3;
                const unsigned BH0 = bh0, BH1 = bh1;
                if (ks + 1 < 8) {
                    const int k16 = 16 * (ks + 1);
                    ldsm4(&Qs[(lane & 15) * DD + (swz(lane & 15, (k16 >> 3) + (lane >> 4), 7) << 3)],
                          a0, a1, a2, a3);
                    ldsm2t(&Sh[(k16 + (lane & 15)) * DV_TILE + (swz(k16 + (lane & 15), nt, 3) << 3)], bh0, bh1);
                }
                mma16816(acc2, A0, A1, A2, A3, BH0, BH1);
            }
            const int i0 = gr, i1 = i0 + 8;
            acco[0] = EX[i0] * acc2[0]; acco[1] = EX[i0] * acc2[1];
            acco[2] = EX[i1] * acc2[2]; acco[3] = EX[i1] * acc2[3];

            float accA[4] = {0.f, 0.f, 0.f, 0.f};
            ldsm4(&khb[(lane & 15) * DD + (swz(lane & 15, lane >> 4, 7) << 3)], a0, a1, a2, a3);
            ldsm2t(&Sh[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], bh0, bh1);
            #pragma unroll
            for (int ks = 0; ks < 8; ++ks) {
                const unsigned A0 = a0, A1 = a1, A2 = a2, A3 = a3;
                const unsigned BH0 = bh0, BH1 = bh1;
                if (ks + 1 < 8) {
                    const int k16 = 16 * (ks + 1);
                    ldsm4(&khb[(lane & 15) * DD + (swz(lane & 15, (k16 >> 3) + (lane >> 4), 7) << 3)],
                          a0, a1, a2, a3);
                    ldsm2t(&Sh[(k16 + (lane & 15)) * DV_TILE + (swz(k16 + (lane & 15), nt, 3) << 3)], bh0, bh1);
                }
                mma16816(accA, A0, A1, A2, A3, BH0, BH1);
            }
            *reinterpret_cast<__half2*>(&Wh[i0 * DV_TILE + (swz(i0, nt, 3) << 3) + 2 * tig]) =
                __halves2half2(f2h(accA[0]), f2h(accA[1]));
            *reinterpret_cast<__half2*>(&Wh[i1 * DV_TILE + (swz(i1, nt, 3) << 3) + 2 * tig]) =
                __halves2half2(f2h(accA[2]), f2h(accA[3]));
        }
        __syncthreads();                                                    // bar2

        // ---- stage chunk c+1 into buffers that are dead after bar2 (Qs, other Kh parity, tables) ----
        if (c + 1 < NC) {
            stage_qk(t0 + CHUNK, (c + 1) & 1);
            if (warp == 0) decay_tables(min(CHUNK, kT - (t0 + CHUNK)), (c + 1) & 1);
        }

        // ---- Ph2: vnew tile nt = Th*Vb + TCc*Wh, produced by every warp that consumes it ----
        const int c2b = (c & 1) * CHUNK;
        unsigned pa0 = 0u, pa1 = 0u, pa2 = 0u, pa3 = 0u;
        if (o_warp) ldsm4(&P[(lane & 15) * CHUNK + ((lane >> 4) << 3)], pa0, pa1, pa2, pa3);
        {
            float acc[4] = {0.f, 0.f, 0.f, 0.f};
            unsigned a0, a1, a2, a3, b0, b1, b2, b3;
            ldsm2t(&Vb[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], b0, b1);
            ldsm2t(&Wh[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], b2, b3);
            ldsm4(Th  + (lane & 15) * 16 + ((lane >> 4) << 3), a0, a1, a2, a3);
            mma16816(acc, a0, a1, a2, a3, b0, b1);
            ldsm4(TCc + (lane & 15) * 16 + ((lane >> 4) << 3), a0, a1, a2, a3);
            mma16816(acc, a0, a1, a2, a3, b2, b3);
            const int i0 = gr, i1 = i0 + 8;
            const int c0 = (swz(i0, nt, 3) << 3) + 2 * tig, c1 = (swz(i1, nt, 3) << 3) + 2 * tig;
            *reinterpret_cast<__half2*>(&Vn2g[i0 * DV_TILE + c0]) =
                __halves2half2(f2h(C2[c2b + i0] * acc[0]), f2h(C2[c2b + i0] * acc[1]));
            *reinterpret_cast<__half2*>(&Vn2g[i1 * DV_TILE + c1]) =
                __halves2half2(f2h(C2[c2b + i1] * acc[2]), f2h(C2[c2b + i1] * acc[3]));
            if (o_warp) {
                *reinterpret_cast<__half2*>(&Vn[i0 * DV_TILE + c0]) = __halves2half2(f2h(acc[0]), f2h(acc[1]));
                *reinterpret_cast<__half2*>(&Vn[i1 * DV_TILE + c1]) = __halves2half2(f2h(acc[2]), f2h(acc[3]));
            }
        }
        __syncwarp();

        // ---- Ph3: S = dl*S + K^T Vn2 (all warps, own tiles);  o = o_inter + P Vn (warps 4-7) ----
        {
            #pragma unroll
            for (int mt = 0; mt < 4; ++mt) {
                Sreg[mt][0] *= dl; Sreg[mt][1] *= dl;
                Sreg[mt][2] *= dl; Sreg[mt][3] *= dl;
            }
            unsigned a0, a1, a2, a3, B0, B1;
            unsigned OB0 = 0u, OB1 = 0u;
            ldsm2t(&Vn2g[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], B0, B1);
            if (o_warp) ldsm2t(&Vn[(lane & 15) * DV_TILE + (swz(lane & 15, nt, 3) << 3)], OB0, OB1);
            ldsm4t(&khb[(lane & 15) * DD + (swz(lane & 15, 2 * mt0 + (lane >> 4), 7) << 3)], a0, a1, a2, a3);
            #pragma unroll
            for (int mt = 0; mt < 4; ++mt) {
                const unsigned A0 = a0, A1 = a1, A2 = a2, A3 = a3;
                if (mt + 1 < 4) {
                    ldsm4t(&khb[(lane & 15) * DD + (swz(lane & 15, 2 * (mt0 + mt + 1) + (lane >> 4), 7) << 3)],
                           a0, a1, a2, a3);
                }
                mma16816(Sreg[mt], A0, A2, A1, A3, B0, B1);
                if (o_warp && mt == 0) mma16816(acco, pa0, pa1, pa2, pa3, OB0, OB1);
            }
            if (o_warp) {
                const int jj = 8 * nt + 2 * tig;
                const int tA = t0 + gr, tB = tA + 8;
                if (tA < kT)
                    *reinterpret_cast<float2*>(op + ((long long)tA * kHv + h) * kD + dv0 + jj) =
                        make_float2(acco[0], acco[1]);
                if (tB < kT)
                    *reinterpret_cast<float2*>(op + ((long long)tB * kHv + h) * kD + dv0 + jj) =
                        make_float2(acco[2], acco[3]);
            }
            if (c + 1 < NC) sts_sh();
        }
        __syncthreads();                                                    // bar4
    }

    // st[v][k] <- S[k][v], into ggml's [v][k]
    {
        float* __restrict__ sth = stp + (long long)h * kD * kD + (long long)(dv0 + jbase) * kD;
        #pragma unroll
        for (int mt = 0; mt < 4; ++mt) {
            const int d0 = 16 * (mt0 + mt) + gr;
            sth[d0]     = Sreg[mt][0];    sth[kD + d0]     = Sreg[mt][1];
            sth[d0 + 8] = Sreg[mt][2];    sth[kD + d0 + 8] = Sreg[mt][3];
        }
    }
#endif // GDN_FUSED_AVAILABLE
}

// The fused kernel's grid is n_v_heads * (head_dim / 32) blocks per sequence; it was
// tuned on GA102 (RTX 3090, 82 SMs) and under-fills larger boards, so by default it is
// used only where the SM count is at most GA102-class; the three-stage chunked kernel
// keeps larger boards until someone tunes there. Compile-time overrides (same style as
// GGML_CUDA_NO_GDN_CHUNK): GGML_CUDA_FORCE_GDN_FUSED selects it everywhere (for
// benchmarking on bigger boards), GGML_CUDA_NO_GDN_FUSED restores the three-stage path.
bool ggml_cuda_gdn_use_fused_chunked(void) {
#if defined(GGML_CUDA_NO_GDN_FUSED)
    return false;
#elif defined(GGML_CUDA_FORCE_GDN_FUSED)
    return true;
#else
    return ggml_cuda_info().devices[ggml_cuda_get_device()].nsm <= 84;
#endif // GGML_CUDA_NO_GDN_FUSED
}

void ggml_cuda_op_gated_delta_net_chunked_fused(ggml_backend_cuda_context & ctx, ggml_tensor * dst,
                                                const ggml_cuda_gated_delta_net_fused_cache * cache) {
    const ggml_tensor * src_q     = dst->src[0];
    const ggml_tensor * src_k     = dst->src[1];
    const ggml_tensor * src_v     = dst->src[2];
    const ggml_tensor * src_g     = dst->src[3];
    const ggml_tensor * src_beta  = dst->src[4];
    const ggml_tensor * src_state = dst->src[5];

    const int V_dim = (int) src_v->ne[0];
    const int H     = (int) src_v->ne[1];
    const int T     = (int) src_v->ne[2];
    const int B     = (int) src_v->ne[3];
    const int K_dim = (int) src_q->ne[0];
    const int Hk    = (int) src_q->ne[1];

    // The kernel is specialised for d=128 (fragment geometry, SMEM sizing); the routing
    // predicate in gated_delta_net.cu already guarantees it.
    GGML_ASSERT(K_dim == 128 && V_dim == 128);
    GGML_ASSERT(H % Hk == 0);

    const long long v_tok_stride = (long long) (src_v->nb[2] / ggml_type_size(src_v->type));

    const float * q_in = (const float *) src_q->data;
    const float * k_in = (const float *) src_k->data;
    const float * v_in = (const float *) src_v->data;
    const float * g_in = (const float *) src_g->data;
    const float * b_in = (const float *) src_beta->data;
    const float * s_in = (const float *) src_state->data;

    // dst = [attn output (V_dim, H, T, B) | final state (K_dim, V_dim, H, B)].
    // When fusing with the state cache copy (cache != nullptr), write the final state directly to
    // the cache pointer instead of the default tail of dst->data -- same contract as the
    // three-stage path. The routing predicate guarantees K == 1, so there is a single snapshot.
    float * out       = (float *) dst->data;
    float * state_out = (cache != nullptr) ? cache->data : out + (int64_t) V_dim * H * T * B;

    const int DTiles = V_dim / DV_TILE;   // dv slabs per head -> grid = H * DTiles blocks
    cudaStream_t stream = ctx.stream();

    // Sequences are independent: blockIdx.y = sequence, the kernel offsets its own pointers.
    gdn_fused<<<dim3(H * DTiles, B), dim3(NTHREADS), 0, stream>>>(
        T, Hk, H, K_dim, q_in, k_in, v_in, g_in, b_in, out, s_in, state_out, v_tok_stride);
    CUDA_CHECK(cudaGetLastError());
}
